# Generated by Django 4.1.7 on 2023-05-02 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tindahan', '0002_products_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oname', models.CharField(max_length=1000)),
                ('oprice', models.IntegerField()),
                ('location', models.CharField(max_length=255)),
                ('custname', models.CharField(max_length=255)),
            ],
        ),
    ]
