# Generated by Django 4.2.2 on 2023-06-08 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tindahan', '0005_alter_orders_custname_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='custname',
            field=models.CharField(max_length=250),
        ),
    ]
