# Generated by Django 4.2.2 on 2023-06-08 23:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tindahan', '0007_orders_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='custname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
