# Generated by Django 4.2.2 on 2023-06-09 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tindahan', '0009_orders_hist_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='hist_pic',
        ),
    ]
