# Generated by Django 4.2.2 on 2023-06-13 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tindahan', '0010_remove_orders_hist_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default=1, upload_to='images/'),
            preserve_default=False,
        ),
    ]
